language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
script:
- python3 -m pytest
- python3 -m pytest --cov-report term --cov=ldaphelper tests/
after_success:
- codecov
deploy:
    provider: pypi
    username: "__token__"
    password:
    secure: G8FYuceEZWXhhscVQjktfwEKZBFgTTkksRaL5FIVcCJDtPkIgl9D/uLLc7LYWFhylkIVGg8D2kF4+PHKNDspb/jjLytEvHxm89unoGUxrY2vgcsX10toxdQpIOTNXlvHRxFmVyTq0JWlkm9zT8KPVHBrLs6zX0mmzkPb/DTNb/L+zR0vd8zBFV+h6MgTaOk9Bhn3X9AATlI1NFR5TPtCapYrcq5fFRf8RVzBSlym+NTLLG5Rl4mmPBGHPZjiT9azYsJxNG5ceSxoHg88JNmxT492PsQiGL6PKm+3lzAPKWoZKwt0CkhHqiSLzl9VGkM7IFGUIWbeRK24HTpSYqytlWMZmG5113HNGbmGa/ejElntVVmF0LhpY/VWq5CZgPIZ6PaijFqsoOtp7U2epEH7Z5v4vBDc4agqeXV1GIy/9s27tDpdHJjgYoYWf8DTQ9wGAD5FbEKK+JwH4Vmq13xyNo4+tRNKtqLTfcXhilRZ7unUx+kotIGnMtzSznuh8+SmtvWsW1eFSU4cERe7PYQ/51o9Mt6UzAQe5P8YQjwcsmoPgOJ75oibT0TCbYEXKgGxENCxlm2RfON2TlRnmzxzh7xYbnEaLWoeqzXC8+y54antRDU9JZPF7oislKQAGiQcJcCZjfPRWc/KjjQ4ihD8Fre5VAyyPbv8+rABik50Jtk=
